---
title: "Data simulation test"
author: "Pitchayen S."
date: "1/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objective

After scenario generation, the data should be simulate and test the calculation logic

```{r}
library(tidyverse)
library(lubridate)
```


## Data generation

```{r}
dt <- tibble(
  case = 1:6,
  launch_date = ymd("2019-01-01"),
  start_date = ymd(c("2019-01-10", "2019-01-10", "2019-01-7", "2019-01-7", "2019-01-8", "2019-01-5")),
  end_date = ymd(c("2019-01-16", "2019-01-19", "2019-01-13", "2019-01-16", "2019-01-14", "2019-01-14"))
)

dt %>% 
  mutate(duration = as.numeric(end_date - start_date) + 1) -> dt

dt
```

```{r}
lam_sim <- tibble(
  age_week = 1:5,
  lambda = 10:6
)

lam_sim
```

## Calculating week and fraction

```{r}
dt %>% 
  mutate(w_start = ceiling(as.numeric(start_date - launch_date)/7), 
         w_end = ceiling(as.numeric(end_date - launch_date)/7), 
         frac_start = (7 - (day(start_date) %% 7)) +1, 
         frac_end = day(end_date) %% 7) -> dt_cal

dt_cal %>% 
  select(case, duration:frac_end)
```

# Override value by case

```{r}
dt_cal %>% 
  mutate(w_between = ifelse(as.numeric(w_end - w_start) > 1, w_start + 1, NA), 
         frac_start = case_when(
           frac_start == 8 ~ 1, 
           frac_start == 7 ~ 0,
           TRUE ~ frac_start
         ), 
         frac_end = ifelse(frac_end == 0, 7, frac_end)
         ) -> dt_mod

dt_mod %>% 
  select(case, duration:w_between)
```

## Mapping with lambda

```{r}
dt_mod %>% 
  left_join(lam_sim, by = c("w_start"="age_week")) %>% 
  left_join(lam_sim, by = c("w_between"="age_week"), suffix = c("","_w_between")) %>% 
  left_join(lam_sim, by = c("w_end"="age_week"), suffix = c("","_w_end")) %>% 
  rename(lambda_w_start = lambda) %>% 
  mutate(lambda_w_between = ifelse(is.na(lambda_w_between), 0, lambda_w_between)) -> dt_join

dt_join %>% 
  select(case, lambda_w_start:lambda_w_end)
```

## Calculating final output

```{r}
dt_join %>% 
  mutate(sum_lambda = ((frac_start/7)*lambda_w_start) + (lambda_w_between) + ((frac_end/7)*lambda_w_end)) %>% 
  select(case, lambda_w_start:sum_lambda)
```

